---
all:
  hosts:
    amazon-linux-1:
      ansible_user: ec2-user
      ansible_host: 10.0.1.101
    amazon-linux-2:
      ansible_user: ec2-user
      ansible_host: 10.0.2.10
    debian:
      ansible_user: admin
      ansible_host: 10.0.1.102
    rocky-linux-1:
      ansible_user: rocky
      ansible_host: 10.0.1.103
    rocky-linux-2:
      ansible_user: rocky
      ansible_host: 10.0.1.104
    rocky-linux-3:
      ansible_user: rocky
      ansible_host: 10.0.1.105
    ubuntu:
      ansible_user: ubuntu
      ansible_host: 10.0.1.106
    test_unreachable:
      ansible_user: user
      ansible_host: 10.0.1.110
    splunk:
      ansible_user: ec2-user
      ansible_host: 10.0.1.210
